#server:
#  port: 8090
#  shutdown: graceful
#spring:
#  autoconfigure:
#    exclude:
#  lifecycle:
#    # 스프링부트가 종료 요청을 받은 후 기다려줄 수 있는 최대한의 시간
#    timeout-per-shutdown-phase: 1h
##  data:
##    redis:
##      host: 172.17.0.1
##      port: 6379
##      password: ${custom.secret.spring.data.redis.password}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#        highlight_sql: false
#        use_sql_comments: false
#logging:
#  level:
#    com.ll.demo03: INFO
#    org.hibernate.SQL: INFO
#    org.hibernate.orm.jdbc.bind: INFO
#    org.hibernate.orm.jdbc.extract: INFO
#    org.springframework.transaction.interceptor: INFO
#custom:
#  prod:
#    cookieDomain: stocknote.kknaks.site
#    frontUrl: "https://www.${custom.prod.cookieDomain}"
#    backUrl: "https://api.${custom.prod.cookieDomain}"
#  site:
#    name: "StockNote"
#    cookieDomain: "${custom.prod.cookieDomain}"
#    frontUrl: "${custom.prod.frontUrl}"
#    backUrl: "${custom.prod.backUrl}"
